# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 01:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDetails',
            fields=[
                ('attandance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('studentMacAddress', models.CharField(max_length=200)),
                ('raspPieMacAddress', models.CharField(max_length=200)),
                ('attendanceStatus', models.CharField(max_length=200)),
                ('classId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassDetails',
            fields=[
                ('className', models.CharField(max_length=200)),
                ('classId', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClassProfessorMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('classId', models.IntegerField()),
                ('professorId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorDetails',
            fields=[
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('professorId', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('studentId', models.IntegerField(primary_key=True, serialize=False)),
                ('macAddress', models.CharField(max_length=200)),
            ],
        ),
    ]
